# Generated by Django 5.1 on 2024-08-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
