# Generated by Django 5.1 on 2024-08-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0002_alter_user_aadhar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
