# Generated by Django 5.1 on 2024-08-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0004_rename_uuid_user_unique_user_id_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unique_user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='aadhar_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
