# Generated by Django 5.1 on 2024-08-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0005_remove_user_id_remove_user_unique_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='unique_user_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
