# Generated by Django 5.1 on 2024-08-20 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0006_loan_unique_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='user',
        ),
        migrations.AlterField(
            model_name='loan',
            name='unique_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loanapp.user'),
        ),
    ]
