# Generated by Django 5.1 on 2024-08-20 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0007_remove_loan_user_alter_loan_unique_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(default='s', on_delete=django.db.models.deletion.CASCADE, to='loanapp.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='unique_user_id',
            field=models.CharField(default='s', max_length=50),
        ),
    ]
