# Generated by Django 5.1 on 2024-08-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0008_loan_user_alter_loan_unique_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_amount_due',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
