# Generated by Django 5.1 on 2024-08-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0009_alter_loan_remaining_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='emi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
