# Generated by Django 5.1 on 2024-08-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0010_loan_emi'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='last_emi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
