# Generated by Django 5.1 on 2024-08-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0013_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='unique_user_id',
        ),
    ]
